INSERT INTO starwars (type, name) VALUES
  ('planets', 'tatooine'),
  ('planets', 'naboo'),
  ('planets', 'mustafar'),
  ('spaceships', 'imperial shuttle'),
  ('spaceships', 'executor'),
  ('spaceships', 'home one'),
  ('vehicles', 'sand crawler'),
  ('vehicles', 'republic cruiser'),
  ('vehicles', 'star destroyer'),
  ('people', 'luke skywalker'),
  ('people', 'han solo'),
  ('people', 'darth wader'),
  ('films', 'the empire strikes back'),
  ('films', 'the return of jedi'),
  ('films', 'the rise of skywalker'),
  ('species', 'albunione yoda'),
  ('species', 'yoda purpurata'),
  ('species', 'polemistus vaderi');